### ISSUE TITLE
Updating an exported service is not handled

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/lighthouse#645]
**What happened**:
In a working setup, when a service is exported, we can successfully access it from remote clusters.
If we update the service (like the port numbers) in the origin cluster, the corresponding serviceImport is not updated.

**Comment by sridhargaddam** [comment]
CC: @aswinsuryan @vthapar

**Comment by nyechiel** [comment]
@donaldh @davidohana this was recently discussed, but realistically not going to happen for 0.12 unless you/someone else are going to work on this before March 3 (rc0). Unless you are planning to pick it up, we should remove it from the 0.12 board.

**Comment by elevran** [comment]
@nyechiel the work plans to tackle that but it is not currently planned to complete in time for 0.12 or be done on the main repo (we're mostly evaluating options via PoC based on the service model review comments).
However, I'll take a quick look and see if it's something that can get a fix for in time or not. Will update around mid this week

**Comment by elevran** [comment]
@nyechiel - spent half a day on analyzing and understanding the code flows and needed tests. 
The fix for changing services specification really requires that Submariner also handle "Conflict" status correctly (e.g., if you only change one of the Service specifications) for all relevant Global Parameter cases. I'm unclear whether this is currently handled (seems not). Therefore, please remove it from the 0.12 board.
